Feature/Client Books TimeSlots for Pets
MonChenil/monchenil pull request #16
Opened 2024-05-19 12:00 UTC by loganSIO

The actual branch name is not explicit, but I changed the title.
This PR refers to this issue : #https://github.com/MonChenil/monchenil/issues/11

2024-05-19 17:56 UTC, samymsa requested changes
Nice 1st PR.

Check the comments and update your tests accordingly 😉

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Services/TimeSlotService.cs
> +    private bool ArePetsIncompatible(Pet pet1, Pet pet2)
Rename to ArePetsCompatible()
Change calls from ArePetsIncompatible() to !ArePetsCompatible()

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Services/TimeSlotService.cs
> +        return (pet1.Type == PetType.Cat && pet2.Type == PetType.Dog) ||
Update the logic :
Pets are compatible if :
- pet1.IncompatibleTypes does not contain pet2.Type
AND
- pet2.IncompatibleTypes does not contain pet1.Type

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Services/TimeSlotService.cs
> +        if (timeSlot == null)
timeSlot cannot be null. Remove this unnecessary check

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Services/TimeSlotService.cs
> +        if (pets == null || !pets.Any())
pets cannot be null. Remove this unnecessary check. You can leave the pets.Any() check

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Services/TimeSlotService.cs
> +    public void AddPetToTimeSlot(TimeSlot timeSlot, IEnumerable<Pet> pets)
Rename to AddPetsToTimeSlot (plural)

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Services/TimeSlotService.cs
> +    public void BookTimeSlotForPets(TimeSlot timeSlot, IEnumerable<Pet> pets)
This looks like a duplicate of AddPetsToTimeSlot()

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Services/TimeSlotService.cs
> +    public IEnumerable<TimeSlot> GetAvailableTimeSlots()
Take a list of pets as parameter
Filter the list of TimeSlots: Only return time slots that can be booked for the given pets. In other words, only return time slots for which there is no compatibility conflict with the given pets.

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Entities/TimeSlot.cs
> -    public List<Pet> Pets { get; set; } = [];
Why?

2024-05-19 17:56 UTC, samymsa commented on backend/MonChenil/Entities/Pet.cs
> +    public Pet()
Don't initialize incompatible pets. Let the user specify that.

2024-05-20 17:02 UTC, closed without merging

2024-05-20 17:17 UTC, loganSIO commented
Every modification requests are made in this PR #https://github.com/MonChenil/monchenil/pull/23